ALTER TABLE users ADD COLUMN nickname VARCHAR(128) NOT NULL DEFAULT '' AFTER uid;
ALTER TABLE users ADD COLUMN email VARCHAR(256) NOT NULL DEFAULT '' AFTER nickname;
ALTER TABLE users ADD COLUMN avatar_url TEXT AFTER email;
ALTER TABLE users ADD COLUMN last_login DATETIME AFTER created_at;
